### ISSUE TITLE
xmls and masks

### ISSUE THREAD

**Issue by Sarvesh-Angadi** [vijendra1125/Tensorfow_Object_detection_API-Custom_Mask_RCNN#1]
Hey,I was following your tutorial but i am not able to get about xmls and masks in annotation folder.

**Comment by vijendraxsingh** [comment]
You will not get any xml file but just masks. Mask will be saved in the directory of image and then you need to move colored masks to annotation folder. Follow https://www.youtube.com/watch?v=tX-xcg5wY4U&t=171s

**Comment by Sarvesh-Angadi** [comment]
Yeah thanks,that helped.

**Comment by vijendraxsingh** [comment]
I am glad to know that it helped.
