### ISSUE TITLE
is possible to use this model without labelling the objects in boxes?

### ISSUE THREAD

**Issue by lfsuarezu** [vijendra1125/Tensorfow_Object_detection_API-Custom_Mask_RCNN#10]
Hi! I just have a question related to the labelling of  the images .,.i need to use something similar to your model of segmentation, but i need that the final images there not cover by a box around the objets detected. Is possible to do this in your model ? .. for example, changing the labelling part?

Thanks

**Comment by vijendraxsingh** [comment]
Yes it is possible. “visualize_boxes_and_labels_on_image_array” function is used in evaluation script to overlay mask and boxes on final image. You will have to check this function for disabling the overlay of boxes on final image. You could find this function in object_detection/utils/ visualisation_utils.py
