### ISSUE TITLE
Where is train.record?

### ISSUE THREAD

**Issue by K-M-Ibrahim-Khalilullah** [vijendra1125/Tensorfow_Object_detection_API-Custom_Mask_RCNN#21]
@vijendra1125 
Thanks for your great works.
I run the file named "create_mask_rcnn_tf_record.py" and it saves the following file:
"data-00000-of-00001", as I see in your repo.

but where is train.record?
From your config file I see the line:
input_path: '/content/drive/learning/DL/projects/object_detection/multiple_object_mask/dataset/train.record'
So How can I get it? 
Would you give some suggestion please?

**Comment by tealeeseng** [comment]
you may rename data-00000-of-00001 to train.record and it will be working fine for training.
