### ISSUE TITLE
Tensorflow 2.x

### ISSUE THREAD

**Issue by darwinOne** [vijendra1125/Tensorfow_Object_detection_API-Custom_Mask_RCNN#33]
@vijendra1125 Thank you for sharing this awesome project.
I want to ask, can this program be used for Tensorflow 2.x?

**Comment by vijendraxsingh** [comment]
@darwinOne  It will need some modifications to make it compatible with Tensorflow 2.x whereas modifications should not be huge.

**Comment by darwinOne** [comment]
@vijendra1125 Thank you for replying.
Can you provide instructions on the parts that need to be modified?

Then, where can I get the .xml file for the train_bboxes folder?

**Comment by vijendraxsingh** [comment]
@darwinOne I have not tried myself to run it with Tensorflow 2 so I can't give you precise instructions for modificaton.

Regarding .xml file, you need to generate it by labeling bounding boxes. Check the blog mentioned in readme for more.

**Comment by darwinOne** [comment]
@vijendra1125 Thanks, I've found the solution and it's working fine.
I will close this issue.
