### ISSUE TITLE
extra labels being detected during tf.record generation

### ISSUE THREAD

**Issue by tanmaypandey7** [vijendra1125/Tensorfow_Object_detection_API-Custom_Mask_RCNN#6]
Hi, my program is detecting fake labels during tf.record script. 
Uploading some screenshot of anaconda:
![screenshot 30](https://user-images.githubusercontent.com/36691630/52844134-eeb88100-3129-11e9-96bc-070ef9bae519.png)
![screenshot 31](https://user-images.githubusercontent.com/36691630/52844137-ef511780-3129-11e9-965e-7511cc0eabbb.png)
Uploading images showing error:
a_100.png:
![a_100](https://user-images.githubusercontent.com/36691630/52844323-5b338000-312a-11e9-946f-904ca43538aa.png)
a_101.png:
![a_101](https://user-images.githubusercontent.com/36691630/52844324-5bcc1680-312a-11e9-8d6f-56eb3f274f79.png)
a_102.png:
![a_102](https://user-images.githubusercontent.com/36691630/52844325-5bcc1680-312a-11e9-95b9-fdb006911f8c.png)
a_103.png:
![a_103](https://user-images.githubusercontent.com/36691630/52844326-5c64ad00-312a-11e9-883a-23bf858c7123.png)
a_104.png:
![a_104](https://user-images.githubusercontent.com/36691630/52844328-5c64ad00-312a-11e9-9c99-c3c61bc116c5.png)
a_105
![a_105](https://user-images.githubusercontent.com/36691630/52844329-5c64ad00-312a-11e9-8d05-4d48a087d2be.png)
a_106
![a_106](https://user-images.githubusercontent.com/36691630/52844330-5cfd4380-312a-11e9-9c36-3df280fb2416.png)
a_107
![a_107](https://user-images.githubusercontent.com/36691630/52844331-5cfd4380-312a-11e9-8e2e-4b863a2d3b1f.png)
a_108
![a_108](https://user-images.githubusercontent.com/36691630/52844333-5d95da00-312a-11e9-9d14-567ad0fdb160.png)
a_109
![a_109](https://user-images.githubusercontent.com/36691630/52844334-5d95da00-312a-11e9-81a4-6c1f40676407.png)
a_110
![a_110](https://user-images.githubusercontent.com/36691630/52844335-5e2e7080-312a-11e9-8a06-cea0962ca041.png)
a_111
![a_111](https://user-images.githubusercontent.com/36691630/52844336-5ec70700-312a-11e9-98bc-bd8e6f4a4569.png)
a_112
![a_112](https://user-images.githubusercontent.com/36691630/52844338-5ec70700-312a-11e9-9b71-006bd3f02863.png)
a_113
![a_113](https://user-images.githubusercontent.com/36691630/52844339-5f5f9d80-312a-11e9-94ad-2d5fc31e2b2a.png)
a_114
![a_114](https://user-images.githubusercontent.com/36691630/52844340-5ff83400-312a-11e9-9446-5e6ac8f30f9c.png)
a_115
![a_115](https://user-images.githubusercontent.com/36691630/52844341-5ff83400-312a-11e9-980f-513b25091ddb.png)
a_116
![a_116](https://user-images.githubusercontent.com/36691630/52844342-6090ca80-312a-11e9-922a-03b3ce3c7016.png)
a_117
![a_117](https://user-images.githubusercontent.com/36691630/52844343-6090ca80-312a-11e9-9528-6d4a8179ef50.png)
a_118
![a_118](https://user-images.githubusercontent.com/36691630/52844344-61296100-312a-11e9-8677-33ad5404ef01.png)
a_119
![a_119](https://user-images.githubusercontent.com/36691630/52844346-61296100-312a-11e9-8cad-5c7990fd39e6.png)
a_120
![a_120](https://user-images.githubusercontent.com/36691630/52844347-61c1f780-312a-11e9-91c9-645949544790.png)
a_121
![a_121](https://user-images.githubusercontent.com/36691630/52844349-625a8e00-312a-11e9-9a03-17ee99235851.png)
a_122
![a_122](https://user-images.githubusercontent.com/36691630/52844350-625a8e00-312a-11e9-9cc8-641c85d8ab06.png)
a_123
![a_123](https://user-images.githubusercontent.com/36691630/52844353-62f32480-312a-11e9-900e-b545a634bbdf.png)
a_124
![a_124](https://user-images.githubusercontent.com/36691630/52844355-638bbb00-312a-11e9-88f4-4c559841bf5c.png)
a_125
![a_125](https://user-images.githubusercontent.com/36691630/52844356-638bbb00-312a-11e9-94ce-6254da49dbdb.png)
a_126
![a_126](https://user-images.githubusercontent.com/36691630/52844322-5b338000-312a-11e9-9bdc-40508cac6cec.png)
I think that it could be due to this weird border surrounding the images. Is it possible to remove this border, if that is causing it?

**Comment by vijendraxsingh** [comment]
What is the number of classes you have and what pixel value are you assigning for each class? 
Please share your label.pbtxt and create_mask_rcnn_tf_record.py

**Comment by tanmaypandey7** [comment]
I opened an issue in the PixelAnnotationTool library and they have fixed this issue in the latest version 1.3.2 
I will report if i encounter any other problems.

**Comment by vijendraxsingh** [comment]
Great! Can you please share link of the issue you opened in the PixelAnnotationTool library.

**Comment by tanmaypandey7** [comment]
Here you go.
https://github.com/abreheret/PixelAnnotationTool/issues/31

**Comment by vijendraxsingh** [comment]
Thank you!
